FROM node:8.9.4

# This Dockerfile assumes that you have built production code using npm run compile
ENV http_proxy "http://192.168.1.1:8123"
ENV https_proxy $http_proxy
ENV no_proxy "localhost, 127.0.0.1"

EXPOSE 3005
WORKDIR /

COPY package.json /
ENV NODE_ENV=production
RUN npm prune
COPY ./dist /
COPY ./node_modules /node_modules
CMD ["node", "index.js"]
