node('docker') {
  stage('Checkout'){
    checkout scm
  }
  stage('Build Docker'){
    withCredentials([ usernamePassword(credentialsId: 'dockerhubess',usernameVariable: 'docker_user',passwordVariable: 'docker_password' )]) {
      sh 'docker login -u essdmscdm -p $docker_password '
      def IMAGE_ID = sh ( script: 'git rev-parse HEAD',returnStdout: true).trim()
      sh "docker build --file CI/ESS/Dockerfile.proxy . --tag dacat/oai-provider-service:latest -t dacat/oai-provider-service:${IMAGE_ID}dev" 
      echo "Git image id : ${IMAGE_ID}"
    }
  }
  stage('Production Build'){
      if (env.BRANCH_NAME == 'develop'){
            def IMAGE_ID = sh ( script: 'git rev-parse HEAD',returnStdout: true).trim()
      sh "docker build --file CI/ESS/Dockerfile.proxy . --tag dacat/oai-provider-service:latest -t dacat/oai-provider-service:${IMAGE_ID}dev" 
      echo "Git image id : ${IMAGE_ID}"
      sh "docker push dacat/oai-provider-service:${IMAGE_ID}dev"
      sh "docker push dacat/oai-provider-service:latest"
      sh "docker rmi dacat/oai-provider-service:${IMAGE_ID}dev"    
      }
  }
}
